name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Python:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
    with:
      db-service: '[""]'
      search-service: '[""]'
